development:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/kontena_development' %>
  options:
    use_utc: true
    raise_not_found_error: false
test:
  sessions:
    default:
      options:
        pool_size: 25
        read: :primary
        write:
          w: 1
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/kontena_test' %>
  options:
    use_utc: true
    raise_not_found_error: false
production:
  sessions:
    default:
      options:
        pool_size: 40
        read: :primary
        write:
          w: 1
      uri: <%= ENV['MONGODB_URI'] || ENV['MONGOHQ_URL'] %>
  options:
    use_utc: true
    raise_not_found_error: false
